/se3controller_node:
  ros__parameters:
    mass: 2.0
    use_external_yaw: true
    gains:
      pos:
        x: 1.0
        y: 1.0
        z: 1.5
      vel:
        x: 2.0
        y: 2.0
        z: 3.0
      ki:
        x: 0.0
        y: 0.0
        z: 0.0
      kib:
        x: 0.0
        y: 0.0
        z: 0.0
      rot:
        x: 1.0
        y: 1.0
        z: 0.5
      ang:
        x: 0.13
        y: 0.13
        z: 0.1
    max_pos_int: 0.5
    mas_pos_int_b: 0.5
    max_tilt_angle: 1.15  # rad
